### ISSUE TITLE
[Question] Is it possible to close the bottom sheets with back button 

### ISSUE THREAD

**Issue by alpayclsr1** [the49ltd/The49.Maui.BottomSheet#121]
I am using the The 49 Maui BottomSheet component. I need some help with handling the Android back button to close the BottomSheet .How can I achieve this?

**Comment by nk-alex** [comment]
You just need to override **OnBackButtonPressed()** on the page it's using the BottomSheet. Then you can use **DismissAsync()** method to dismiss the BottomSheet when back button pressed
