### ISSUE TITLE
In Android, the bottom sheet opens behind a Shell modal page

### ISSUE THREAD

**Issue by drmaven** [the49ltd/The49.Maui.BottomSheet#24]
Suppose a Shell page with PresentationMode=Modal. If I open a bottomsheet from this page, then it does not show on top of the modal page. Instead, i have to close the modal page and then the bottom sheet is displayed.

Expected behavior:
Bottom sheet opens on top of Shell Modal page. 

iOS works fine

**Comment by paulvarache** [comment]
Hi,

Can you confirm which version you noticed this?

I have just tested on the latest version and cannot reproduce

**Comment by CorentinSwiss4** [comment]
I reproduce an issue similar : bottom sheet appear behind a modal page push modal page push bottom sheet.

On iOS the bottom sheet appear in front of all page correctly.

**Comment by sang-hyeon** [comment]
same issue here.

**Comment by madp4ul** [comment]
Tried rc5 and noticed this on android.

To reproduce: Create a new ContentPage and in its constructor set the shell presentation mode to modal:
`Shell.SetPresentationMode(this, PresentationMode.Modal); // this is the page`
or in xaml: `Shell.PresentationMode="Modal"`

Then make the modal page half transparent: `BackgroundColor = new Color(255, 0, 0, 128);` and from the page, trigger a bottom sheet to show up. You will see that it shows up behind the red tint.

By the way in rc2 the bottomSheet.Show() still worked when called from the OnNavigatedTo event of the page. Now with rc5 it does not work anymore, except with a Task.Delay() before calling bottomSheet.ShowAsync(). 
Do you have any recommendations on how to most reliably trigger a bottom sheet when entering a page?

**Comment by paulvarache** [comment]
I have release rc6. In this release, I attach the BottomSheet to the Window of the Android Activity instead of adding it to the navigation manager's root.

This should ensure an open BottomSheet stays on top of pages inside the navigation view.

Please try it out and let me know if that solves it

**Comment by CorentinROBERT** [comment]
unfortunately no improvement on my side, 

the bottom sheet is always displayed behind the modals

cf my video ... 


https://github.com/the49ltd/The49.Maui.BottomSheet/assets/37982988/2d3556fb-af01-4d56-a6f6-4936f22d387d

**Comment by paulvarache** [comment]
I have pushed some changed to a branch called `window`. It rewrites a bunch of Android logic, so I'll hold off on making a release just yet.

I've tested the modal pages scenario and it works locally. If anyone here could give it a go and feedback it would be greatly appreciated.

**Comment by CorentinSwiss4** [comment]
@paulvarache  it's works fine ! 
Can you merge this branch ?

**Comment by paulvarache** [comment]
I just have pushed 1.0.0-rc8 with that fix in

**Comment by 007vel** [comment]
This issue appears again when upgraded to dotnet9
