### ISSUE TITLE
Android: Extra Space over Title after closing a BottomSheet

### ISSUE THREAD

**Issue by troy-ob** [the49ltd/The49.Maui.BottomSheet#28]
An extra white space is added over the title after closing a BottomSheet, see below:

![image](https://github.com/the49code/The49.Maui.BottomSheet/assets/134378785/4000d42c-4b14-4a92-9a36-421c84ca205c)

The space disappears if the bottom sheet is reopened, but appears again after closing.

Steps to reproduce:

1) Create new Maui project
2) Install the the:49:BottomSheet NuGet package - version rc1, and follow the Readme for usage
3) Copied the SimplePage from the Sample. Display the SimplePage-BottomSheet on ButtonClick
4) Build and deploy on Android -> click button

This does not happen with the alpha7 version

**Comment by troy-ob** [comment]
Thanks for the quick reply.

I created ```Platforms/Android/Resources/values/styles.xml``` and added to it:


```<?xml version="1.0" encoding="utf-8" ?>
<resources>
	<style name="Maui.MainTheme" parent="Theme.Material3.DayNight"></style>
</resources>
```

Are there any others steps to take that Android uses this theme?

**Comment by JuanLeenspace** [comment]
Having the same problem here.

**Comment by Jota-Devs** [comment]
Having the same problem here. Any news?

**Comment by paulvarache** [comment]
Hi,

It took some time to figure out what was happening but this is finally fixed in version 1.0.0-rc2 available now

**Comment by troy-ob** [comment]
The update fixed it for me. But I had to add some more bottom-padding to the BottomSheet itself, as the content was cut off by a bit. Couldn't test it on iOS yet

**Comment by paulvarache** [comment]
Hi,

Thanks for reporting this. Can you please both add more information?

 - Are you using Shell or NavigationPage?
 - Which version of Android
 - Which device model

**Comment by gaterin** [comment]
I am using Shell, android version on emulator 11 on physical device is 12, both same issue. using a pixel 5 device on emulator and a xiaomi redmi note 11 pro as physical device.
