### ISSUE TITLE
CornerRadius disappears when fully extended in Android

### ISSUE THREAD

**Issue by mytahir** [the49ltd/The49.Maui.BottomSheet#36]
This issue still happening exactly as @DiogoDeAlmeida explained it on #14, i tried:
var sheet = new MySheet();
sheet.Showing += (s, e) =>
{
sheet.Controller.Behavior.DisableShapeAnimations();
};
sheet.ShowAsync(Window);
But the CornerRadius still animates when extended.

**Comment by DiogoDeAlmeida** [comment]
Hi !

With 1.0.0-rc3 version i have no issue with animation.


```csharp
var sheetInfo = new InfoPopup(parameter, _services);
sheetInfo.Showing += (s, e) =>
 {
#if ANDROID

    sheetInfo.Controller.Behavior.DisableShapeAnimations();

#endif

};
await sheetInfo.ShowAsync(App.Current.Windows.FirstOrDefault());
```


https://github.com/the49ltd/The49.Maui.BottomSheet/assets/67577360/c7460d20-b8b4-4aa6-8780-e7084e1989e5

**Comment by paulvarache** [comment]
I cannot reproduce and @DiogoDeAlmeida either.

@mytahir is this still an issue?

**Comment by mytahir** [comment]
solved. Thank you
