### ISSUE TITLE
Misbehavior with NavigationPage

### ISSUE THREAD

**Issue by hergarcia** [the49ltd/The49.Maui.BottomSheet#42]
When opening the bottom sheet into a navigation page, it expands by cutting off top and bottom of the screen

https://github.com/the49ltd/The49.Maui.BottomSheet/assets/91212752/999ef1e8-1d89-4678-8bfb-b18768bbefa2

**Comment by paulvarache** [comment]
Hi,

The most recent version should have addressed that.

Please re-open an issue if that is not the case
