### ISSUE TITLE
Crash on Android 9 - Missing Method

### ISSUE THREAD

**Issue by pijnappel** [the49ltd/The49.Maui.BottomSheet#44]
the bottom sheet works perfectly on Android 13. On Android 9 it crashes when opening because of a missing method error in 

`BottomSheetController > GetAvailableHeight > GetInsets `

**Comment by hwsmo** [comment]
Yes, this error i can also confirm.

**Comment by paulvarache** [comment]
1.0.1 should appear on nuget soon with a fix for this.

I have not been able to test on an Android 9 device or emulator, but I have safeguarded all usage of the Android SDK using the Compat layer of checking the operating system version.

Let me know if this fixes you issues and I'll close the issue

**Comment by hwsmo** [comment]
Hi Paul, your fix helped. Thx!
