### ISSUE TITLE
Is it possible to have an event when the BottomSheet is closed?

### ISSUE THREAD

**Issue by JairoMarques** [the49ltd/The49.Maui.BottomSheet#45]
In my **BottomSheet** I have some entries. When using modal and clicking outside, **BottomSheet** is closed but the keyboard still visible.

When I use a dismiss button I can set " this.Focus()" to close the keyboard, so if it had an event when **BottomSheet** is closed I could do the same approach.

Any ideas on how to solve this?

**Comment by borrmann** [comment]
The readme says there is a Dismissed Event

**Comment by JairoMarques** [comment]
> The readme says there is a Dismissed Event

Oh, you're right! Thank you!
