### ISSUE TITLE
Issues with <OnPlatform/>

### ISSUE THREAD

**Issue by EdwardMcFlurry** [the49ltd/The49.Maui.BottomSheet#46]
Hi @paulvarache 

Are you aware that using OnPlatform is not woking with your Plugin as I could be wrong but it requires a Type and Value but looking at your example it doesn't work on my side. Below is what I used to have different presentation of the Bottomsheet per platform.

<bottomSheet:BottomSheet.Detents>
        <OnPlatform>
            <On Platform="Android">
                <bottomSheet:RatioDetent Ratio=".50" />
            </On>
            <On Platform="iOS">
                <bottomSheet:MediumDetent />
            </On>
        </OnPlatform>
    </bottomSheet:BottomSheet.Detents>

Kindly advise as to how to go about using OnPlatofrm with the Plugin.

**Comment by EdwardMcFlurry** [comment]
> Hi @paulvarache
> 
> Are you aware that using OnPlatform is not woking with your Plugin as I could be wrong but it requires a Type and Value but looking at your example it doesn't work on my side. Below is what I used to have different presentation of the Bottomsheet per platform.
> 
> bottomSheet:BottomSheet.Detents <bottomSheet:RatioDetent Ratio=".50" /> <bottomSheet:MediumDetent /> </bottomSheet:BottomSheet.Detents>
> 
> Kindly advise as to how to go about using OnPlatofrm with the Plugin.

@jfversluis can you perhaps know of a way to do this per platform?

**Comment by paulvarache** [comment]
Here is a working example:

```xml
    <the49:BottomSheet.Detents>
        <OnPlatform x:TypeArguments="the49:DetentsCollection">
            <On Platform="Android">
                <the49:DetentsCollection>
                    <the49:FullscreenDetent />
                    <the49:RatioDetent Ratio=".95" />
                    <the49:RatioDetent Ratio=".5" />
                </the49:DetentsCollection>
            </On>
            <On Platform="iOS">
                <the49:DetentsCollection>
                    <the49:FullscreenDetent />
                    <the49:RatioDetent Ratio=".95" />
                    <the49:MediumDetent />
                </the49:DetentsCollection>
            </On>
        </OnPlatform>
    </the49:BottomSheet.Detents>
```

I'll have the readme updated to fix the wrong example in the next release.

Let me know if that solves your issue

**Comment by EdwardMcFlurry** [comment]
Hi @paulvarache 

Thanks as it did work however, the BIG problem on Android even from @jfversluis video is the Handle that is missing. On iOS is visible but on Android it is not although 'HasHandle="True"'.

Can you please take a look it?

**Comment by EdwardMcFlurry** [comment]
@paulvarache kindly take a look at this issue on Android if you got the time.

**Comment by EdwardMcFlurry** [comment]
> Hi @paulvarache
> 
> Thanks as it did work however, the BIG problem on Android even from @jfversluis video is the Handle that is missing. On iOS is visible but on Android it is not although 'HasHandle="True"'.
> 
> Can you please take a look it?

@paulvarache, I have added the styles.xml for Android and can now confirm that the Handle shows. Thank you once again for this handful tool 👍🏻
