### ISSUE TITLE
Press the back button, bottomsheet cannot be closed

### ISSUE THREAD

**Issue by xyeie** [the49ltd/The49.Maui.BottomSheet#50]
I am currently using bottomsheet on the Android . When the bottomsheet is open and the device's back button is pressed, the route will back, but the bottomsheet will not be closed. I think under normal circumstances, press the back button will close the bottomsheet, and then press the return button again will execute the routing.

**Comment by paulvarache** [comment]
Hi,

I don't think making this the default behaviour would benefit all scenarios. For example, I sometimes show a bottom sheet that is not cancellable at the bottom of a page and want the back button to navigate back. I then dismiss the sheet when the page disappears.

I believe it may be better to have whichever page is currently displayed override the OnBackButtonPressed. You would then be able to check if the sheet is shown handle the dismiss there is needed.

If using Shell, you can listen to the `Navigating` event, the event args has a Cancel method to prevent the navigation
