### ISSUE TITLE
[Issues] Rounded corners in expanded state


### ISSUE THREAD

**Issue by AntonUA86** [the49ltd/The49.Maui.BottomSheet#51]

**Comment by paulvarache** [comment]
Can't go really far with that little information, but I'll assume this is a duplicate of https://github.com/the49ltd/The49.Maui.BottomSheet/issues/36 and https://github.com/the49ltd/The49.Maui.BottomSheet/issues/14

Also covered by the readme here: https://github.com/the49ltd/The49.Maui.BottomSheet#how-do-i-prevent-the-rounded-corner-to-animate-on-android
