### ISSUE TITLE
Calling the BottomSheet OnAppearing() is causing a crash!!!

### ISSUE THREAD

**Issue by Frizbi22** [the49ltd/The49.Maui.BottomSheet#53]
<?xml version="1.0" encoding="utf-8" ?>

<the49:BottomSheet xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:the49="https://schemas.the49.com/dotnet/2023/maui"
                   Padding="16,32" BackgroundColor="LightGrey" HasHandle="True" HandleColor="Red"
          x:Class="MauiApp2.Controls.BottomSheet">
    <the49:BottomSheet.Detents>
        <the49:MediumDetent />
    </the49:BottomSheet.Detents>
    <ScrollView Padding="32">
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto"/>
                <RowDefinition Height="*"/>
            </Grid.RowDefinitions>
            <BoxView BackgroundColor="Black" HeightRequest="10" WidthRequest="40"/>
            <VerticalStackLayout Spacing="32" Grid.Row="1">
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
            </VerticalStackLayout>
        </Grid>

    </ScrollView>

</the49:BottomSheet>    

protected override void OnAppearing()
    {
        base.OnAppearing();
		try
		{
            var page = new BottomSheet();
            page.ShowAsync(false);
        }
		catch(Exception ex)
		{
			Console.Write(ex.ToString());
		}

    }

**Comment by Frizbi22** [comment]
**Java.Lang.NullPointerException:** ''

**Comment by ac-lap** [comment]
Facing the same issue on upgrading from 1.0.1 to 1.0.4
