### ISSUE TITLE
 HasHandle="True" HandleColor="Red" not working on Android

### ISSUE THREAD

**Issue by Frizbi22** [the49ltd/The49.Maui.BottomSheet#54]
<?xml version="1.0" encoding="utf-8" ?>

<the49:BottomSheet xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:the49="https://schemas.the49.com/dotnet/2023/maui"
                   Padding="16,32" BackgroundColor="LightGrey" HasHandle="True" HandleColor="Red"
          x:Class="MauiApp2.Controls.BottomSheet">
    <the49:BottomSheet.Detents>
        <the49:MediumDetent />
    </the49:BottomSheet.Detents>
    <ScrollView Padding="32">
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto"/>
                <RowDefinition Height="*"/>
            </Grid.RowDefinitions>
            <BoxView BackgroundColor="Black" HeightRequest="10" WidthRequest="40"/>
            <VerticalStackLayout Spacing="32" Grid.Row="1">
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
                <BoxView WidthRequest="120" HeightRequest="120" Color="Salmon" />
            </VerticalStackLayout>
        </Grid>

    </ScrollView>

**Comment by EdwardMcFlurry** [comment]
@Frizbi22 I've also noticed that strange behaviour on Android and wondering why or when will it be fixed.

**Comment by eccforgit** [comment]
I'm having the same problem.  HasHandle=True does nothing.  The first item in the menu is the first item there is 0 real estate above it for the handle to exist.

**Comment by paulvarache** [comment]
Can you please confirm you have updated the Android theme to extend Material 3 as mentioned in the README?

**Comment by t-macintosh** [comment]
I have used your bottom sheets control in a previous Android app using one of the earlier releases (1.0.1) and I've just added the latest version (8.0.3) to a new app. I have added the styles.xml file to extend the Material theme as recommended in the docs, but when the bottom sheet displays the handle doesn't appear.

![image](https://github.com/the49ltd/The49.Maui.BottomSheet/assets/150857444/91e41d54-d0b0-432f-8821-7b30b833ea4e)

xaml code:
```
<the49:BottomSheet xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                   xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                   xmlns:the49="https://schemas.the49.com/dotnet/2023/maui"
                   xmlns:viewmodels="clr-namespace:XXXXXXXXXXXXXXX.ViewModels.Ble"
                   x:DataType="viewmodels:XXXXXXXXXXXX"
                   xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
                   x:Class="XXXXXXXXXXXX.Views.MenuBottomSheet"
                   Background="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource Gray900}}"
                   HasHandle="True"
                   HandleColor="White"
                   CornerRadius="30">
```

Platforms\Android\Resources\values\styles.xml
```
<?xml version="1.0" encoding="utf-8" ?>
<resources>
	<style name="Maui.MainTheme" parent="Theme.Material3.DayNight"></style>
</resources>
```

**Comment by takennnusernames** [comment]
hi, im having the same issue, is there a fix for this already?
