### ISSUE TITLE
Question: Can the BottomSheet be used with a ViewModel?

### ISSUE THREAD

**Issue by tmacintosh** [the49ltd/The49.Maui.BottomSheet#60]
This is simply just a question of whether or not this library supports creating a BottomSheet with a ViewModel. If so do you have any examples of how it would be implemented?

**Comment by paulvarache** [comment]
If can set a viewmodel in your sheet the same way you would any page.

If you're trying to open a sheet from a viewmodel, there are closed issues on this repo that already cover that
