### ISSUE TITLE
Java.Lang.NullPointerException when trying to show BottomSheet

### ISSUE THREAD

**Issue by ac-lap** [the49ltd/The49.Maui.BottomSheet#63]
In my app, I am reusing the same instance of BottomSheet to show and dismiss it multiple times. I am doing this in hope that this is more efficient and will save creation cost of the BottomSheet.

But after first ShowAsync() + DismissAsync() and then ShowAsync() results in app crash with Java.Lang.NullPointerException. Adding a try/catch block on ShowAsync does not catch any exception and the app still crashes.

Questions -

1. Is the BottomSheet instance reuse across multiple show-dismiss supported and is expected to work? If not, then creating a new instance of BottomSheet for every ShowAsync() is the right expectation?
2. If the reuse of the same instance is expected to work, can you plz help me fix this crash issue, or how can I debug this further.

Sample code -

```
_bookBottomSheet = new BookBottomSheet();
_bookBottomSheet.InitializeView(bookData);

_bookBottomSheet.ShowAsync(Window);
_bookBottomSheet.DismissAsync(false);

// Throws Java.Lang.NullPointerException here
_bookBottomSheet.ShowAsync(Window);
```

Following is the stack trace -
![image](https://github.com/the49ltd/The49.Maui.BottomSheet/assets/5137736/3bb11c7a-aebc-44ee-950b-0bbd3e83706f)

**Comment by gabsamples6** [comment]
@paulvarache  hi  this is exactly what we need - we encountered the same error  but  in a different scenario... 

if you want a bottomsheet to be open as soon as you page has loaded this will cause a crash.

1. in the provided sample demo. 
2. Call any of the sheets  -OnNavigated-OnAppearing etc.. and this will crash on rootwindowsinset being null

adding a Task.Delay(1000) or handling the null fixes the issue
![image](https://github.com/the49ltd/The49.Maui.BottomSheet/assets/109357537/03b17ae5-3d75-4981-8718-3a4d8197ada1)

I hope this helps in fixing the issue properly . Not sure if handling a null is the right thing to do there, even though it gets fired multiple times...
