### ISSUE TITLE
Update bottom sheet UI when ViewModel updated

### ISSUE THREAD

**Issue by AliKarimiENT** [the49ltd/The49.Maui.BottomSheet#69]
Hello,

I've encountered an issue where the bottom sheet UI isn't reflecting updates made to the ViewModel data it's bound to. Despite changes occurring in the underlying data, the view remains static and doesn't show the updated state.

Could anyone advise on a solution to ensure the UI stays in sync with the ViewModel updates?

Thank you!

**Comment by paulvarache** [comment]
Hi,

I have used this package in multiples areas of multiple apps and have had no issues with ViewModel bindings not updating.

There is one issue regarding HotReload, where the content of the sheet isn't hot reloadable.

I'd advise you make sure all the bindings are configured correctly, check the BindingContext and use compiled bindings to help find where the issue might be. MAUI also sometimes logs incorrect bindings letting you know which binding is looking for which property in which binding context
