### ISSUE TITLE
Margin around Handle

### ISSUE THREAD

**Issue by hansmbakker** [the49ltd/The49.Maui.BottomSheet#82]
Hi,
I see the `Handle` is just drawn on top of the BottomSheet - it does not seem to have its own margin, resulting in content being placed below it:

<img width="299" alt="image" src="https://github.com/the49ltd/The49.Maui.BottomSheet/assets/3463496/821cc721-07c3-43ee-8f9c-ba4695dee9e0">

The code used is
```xaml
<the49:BottomSheet xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                   xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                   xmlns:the49="https://schemas.the49.com/dotnet/2023/maui"
                   x:Class="MyNamespace.MyClass"
                   HasHandle="True"
                   IsCancelable="True"
                   HasBackdrop="True"
                   CornerRadius="16"
                   BackgroundColor="White">
    <!-- Content of control here -->
</the49:BottomSheet>
```

Is this intended behavior?

**Comment by paulvarache** [comment]
It is intended, so that content can be placed at the top of the sheet. For example, people may want to add a close button on the top right of the sheet and need access to that space under the handle.

Your best option for now would be adding a padding to your layout in the sheet
