### ISSUE TITLE
iOS 15.5 Detents Not Working 

### ISSUE THREAD

**Issue by alpayclsr1** [the49ltd/The49.Maui.BottomSheet#86]
Unless I set the Detent to fullscreen, it opens in medium detent, the Anchor Detent and Content Detent functionalities do not work on iOS 15.5 devices.

**Comment by paulvarache** [comment]
Custom detents on iOS are only supported from iOS 16 and up: https://developer.apple.com/documentation/uikit/uisheetpresentationcontroller/detent/3976719-custom

On iOS 15 and down, the only detents supported are medium and large, which translate to a RatioDetent with 0.5 and a FulScreenDetent

This is also mentioned in the readme
