### ISSUE TITLE
Suggestion: Setup github actions

### ISSUE THREAD

**Issue by hansmbakker** [the49ltd/The49.Maui.BottomSheet#87]
I would like to suggest setting up github actions to automatically
- validate PRs
- publish new versions of the nuget package, for example when a PR is merged

This would make checking of PRs less time-consuming and it would also fix the current situation where bugs are fixed in the repo but not published (#77).

I'd be happy to help with this, but I have no access to the nuget feed of this package and I think the rules for when a new version is packaged need to be agreed upon.

**Comment by paulvarache** [comment]
I agree. Having builds for PRs to check that it at least builds correctly, then pushing to nuget on tags.
I'm not familiar with Github actions but I suspect it's similar to AzureDevops pipelines.

If you want to start looking at this I'd suggest the rules above, simple build on PRs, Release build and push to nuget on tags. I can then add the secret API keys to the nuget feed

**Comment by hansmbakker** [comment]
@paulvarache I created a first contribution at https://github.com/the49ltd/The49.Maui.BottomSheet/pull/91 and there are still some open ends. Let's discuss further there.

**Comment by paulvarache** [comment]
@hansmbakker  I've updated the yaml file you provided and added another one for the nuget feed push. It now should pack and publish an artifact for each open PR targeting `main` so we can easily download and test before merging. I have changes from building the sample app, to packing the package. It means we don't need to build for different platforms and it checks that the package actually builds. WHile it's important to have the sample app functional, I think it's less critical if it breaks for a short while than if the package itself does.

Tagging now packs the package and pushes it to nuget
