### ISSUE TITLE
Support for net8.0

### ISSUE THREAD

**Issue by SimonBrettschneider** [the49ltd/The49.Maui.BottomSheet#90]
Hi

First of all, thank you for the very-needed plugin. 

We have been looking forward to the latest release with net8-android and net8-iOS support) Unfortunately, it does not support .net8.0, which is needed for our integration and unit test projects. Would it be possible to .net8.0 support?

**Comment by paulvarache** [comment]
Yes that's an oversight on my part. This package should support net8.0, net8.0-maccatalyst and net8.0-windows. I'll have an update with this fixed in the next 30min

**Comment by hansmbakker** [comment]
For my understanding, can you explain why you would need all those platforms? The package only works on ios and android as I understand?

**Comment by SimonBrettschneider** [comment]
@paulvarache I am glad for your quick reply and the speedy release, but as far as I can see .net8.0 was left out. Would it be possible to add support for it?

**Comment by hansmbakker** [comment]
Ok, I understand that not having `net8.0` makes it less flexible then.
On the other hand (not having seen your code so maybe this comment won't make sense) if you'd split out the common logic in a `MyApp.Core` project (e.g. viewmodels, helpers, etc) then you wouldn't need that unit test project to reference your UI project - it could be an opportunity to making it more testable.

**Comment by mglochsen** [comment]
> Ok, I understand that not having `net8.0` makes it less flexible then. On the other hand (not having seen your code so maybe this comment won't make sense) if you'd split out the common logic in a `MyApp.Core` project (e.g. viewmodels, helpers, etc) then you wouldn't need that unit test project to reference your UI project - it could be an opportunity to making it more testable.

Yes, you're absolutely right and it is kind of a technical dept in my code to not have such a common project. However I think I'm not the only one having this structure.

**Comment by paulvarache** [comment]
I think adding net8.0 makes sense. This package is setup in a way to work with no underlying platform at all so it doesn't require any extra steps. It also makes the installation for all project a bit easier, no need to conditionally include the package, which is better for everyone.

I think it makes the package slightly bigger, but that has no impact on an app's final build as the toolchain will only include what's needed for each platform.

I'll try to add it in and make a release soon, hopefully today

**Comment by paulvarache** [comment]
I have pushed a new version with net8.0 added as a target

**Comment by mglochsen** [comment]
Thanks a lot, I can confirm that net8.0 is supported and my project builds without any problems.

**Comment by SimonBrettschneider** [comment]
Thank you! I can confirm that it works.
