### ISSUE TITLE
[Android] Dismissing a sheet may cause System.NullReferenceException

### ISSUE THREAD

**Issue by MarcAlx** [the49ltd/The49.Maui.BottomSheet#93]
Observed on 8.0.2 version. This happen occasionally when dismissing a sheet programmatically or via gesture. Mainly after many open/close of the same sheet.

Observed on Android 10 (physical device).

For reference here's the underlaying exception:

```
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
[mono-rt]    at The49.Maui.BottomSheet.ContentDetent.GetHeight(BottomSheet page, Double maxSheetHeight)
[mono-rt]    at The49.Maui.BottomSheet.BottomSheetController.CalculateHeights(Double maxSheetHeight)
[mono-rt]    at The49.Maui.BottomSheet.BottomSheetController.<OnLayoutChange>b__56_0()
[mono-rt]    at Microsoft.Maui.Dispatching.Dispatcher.<>c__DisplayClass4_0.<DispatchImplementation>b__0() in D:\a\_work\1\s\src\Core\src\Dispatching\Dispatcher.Android.cs:line 24
[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.IRunnable.cs:line 84
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 26
```

**Comment by chrisrouw** [comment]
I'm seeing the same issue on both a simulator and physical device. The physical device is using Android 12.

System.NullReferenceException: Object reference not set to an instance of an object

The49.Maui.BottomSheet.ContentDetent.GetHeight(BottomSheet page, Double maxSheetHeight)
The49.Maui.BottomSheet.BottomSheetController.CalculateHeights(Double maxSheetHeight)
The49.Maui.BottomSheet.BottomSheetController.<OnLayoutChange>b__56_0()
Microsoft.Maui.Dispatching.Dispatcher.<>c__DisplayClass4_0.<DispatchImplementation>b__0()
Java.Lang.Thread.RunnableImplementor.Run()
Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)

**Comment by pijnappel** [comment]
Same issue here, using Android 9. Has anyone found a workaround?

**Comment by hergarcia** [comment]
Same issue here, waiting for a workaround...

**Comment by coop-tim** [comment]
I see the same on iOS and it's thrown when you've already dismissed the sheet programmatically but then the page it was created from is disposed. Causes application crash, my only workaround currently is to not dismiss it programmatically.

**Comment by AbbasTabikh** [comment]
Same here... sometimes it works for like 5 times, some other times  it throws after the first dismiss

**Comment by MarcAlx** [comment]
> I see the same on iOS and it's thrown when you've already dismissed the sheet programmatically but then the page it was created from is disposed. Causes application crash, my only workaround currently is to not dismiss it programmatically.

I open an issue for your specific problem: https://github.com/the49ltd/The49.Maui.BottomSheet/issues/94

**Comment by borrmann** [comment]
> We have found the NRE position. https://github.com/the49ltd/The49.Maui.BottomSheet/blob/main/src/Models/ContentDetent.cs#L15 `page.window.width` the `Window` property is null here.
> 
> At the moment we don't know why this property is null in some cases.
> 
> **Workaround**
> 
> ```
> public class FixedContentDetent : ContentDetent
> {
>     // HACK: https://github.com/the49ltd/The49.Maui.BottomSheet/issues/93
>     public override double GetHeight(BottomSheet page, double maxSheetHeight)
>     {
>         if (page.Content is null)
>         {
>             return maxSheetHeight;
>         }
> 
>         if (page.Content is ScrollView sv)
>         {
>             var s = sv.Content.Measure(page.Window.Width - page.Padding.HorizontalThickness, maxSheetHeight);
>         }
>         // HACK: from 'page.Window.Width' to 'page.Window?.Width ?? page.Width' 
>         var r = page.Content.Measure(page.Window?.Width ?? page.Width - page.Padding.HorizontalThickness, maxSheetHeight);
> 
>         return Math.Min(maxSheetHeight, r.Request.Height + page.Padding.VerticalThickness);
>     }
> }
> ```

I still caught some exceptions with that (apparently page can be null) but the following code fixed the issue for me

`
public class FixedContentDetent : ContentDetent
{
    // HACK: https://github.com/the49ltd/The49.Maui.BottomSheet/issues/93
    public override double GetHeight(BottomSheet page, double maxSheetHeight)
    {
        if (page?.Content is null)
        {
            return maxSheetHeight;
        }

        // HACK: from 'page.Window.Width' to 'page.Window?.Width ?? page.Width' 
        var r = page.Content.Measure(page.Window?.Width ?? page.Width - page.Padding.HorizontalThickness, maxSheetHeight);

        return Math.Min(maxSheetHeight, r.Request.Height + page.Padding.VerticalThickness);
    }
}
`

**Comment by buluf** [comment]
Same issue here

**Comment by buluf** [comment]
> > We have found the NRE position. https://github.com/the49ltd/The49.Maui.BottomSheet/blob/main/src/Models/ContentDetent.cs#L15 `page.window.width` the `Window` property is null here.
> > At the moment we don't know why this property is null in some cases.
> > **Workaround**
> > ```
> > public class FixedContentDetent : ContentDetent
> > {
> >     // HACK: https://github.com/the49ltd/The49.Maui.BottomSheet/issues/93
> >     public override double GetHeight(BottomSheet page, double maxSheetHeight)
> >     {
> >         if (page.Content is null)
> >         {
> >             return maxSheetHeight;
> >         }
> > 
> >         if (page.Content is ScrollView sv)
> >         {
> >             var s = sv.Content.Measure(page.Window.Width - page.Padding.HorizontalThickness, maxSheetHeight);
> >         }
> >         // HACK: from 'page.Window.Width' to 'page.Window?.Width ?? page.Width' 
> >         var r = page.Content.Measure(page.Window?.Width ?? page.Width - page.Padding.HorizontalThickness, maxSheetHeight);
> > 
> >         return Math.Min(maxSheetHeight, r.Request.Height + page.Padding.VerticalThickness);
> >     }
> > }
> > ```
> 
> I still caught some exceptions with that (apparently page can be null) but the following code fixed the issue for me
> 
> ```
> public class FixedContentDetent : ContentDetent
> {
>     // HACK: https://github.com/the49ltd/The49.Maui.BottomSheet/issues/93
>     public override double GetHeight(BottomSheet page, double maxSheetHeight)
>     {
>         if (page?.Content is null)
>         {
>             return maxSheetHeight;
>         }
> 
>         // HACK: from 'page.Window.Width' to 'page.Window?.Width ?? page.Width' 
>         var r = page.Content.Measure(page.Window?.Width ?? page.Width - page.Padding.HorizontalThickness, maxSheetHeight);
> 
>         return Math.Min(maxSheetHeight, r.Request.Height + page.Padding.VerticalThickness);
>     }
> }
> ```

How do u guys put this override to work? Like where in the project that the bottomSheet get this modification.

**Comment by borrmann** [comment]
> > > We have found the NRE position. https://github.com/the49ltd/The49.Maui.BottomSheet/blob/main/src/Models/ContentDetent.cs#L15 `page.window.width` the `Window` property is null here.
> > > At the moment we don't know why this property is null in some cases.
> > > **Workaround**
> > > ```
> > > public class FixedContentDetent : ContentDetent
> > > {
> > >     // HACK: https://github.com/the49ltd/The49.Maui.BottomSheet/issues/93
> > >     public override double GetHeight(BottomSheet page, double maxSheetHeight)
> > >     {
> > >         if (page.Content is null)
> > >         {
> > >             return maxSheetHeight;
> > >         }
> > > 
> > >         if (page.Content is ScrollView sv)
> > >         {
> > >             var s = sv.Content.Measure(page.Window.Width - page.Padding.HorizontalThickness, maxSheetHeight);
> > >         }
> > >         // HACK: from 'page.Window.Width' to 'page.Window?.Width ?? page.Width' 
> > >         var r = page.Content.Measure(page.Window?.Width ?? page.Width - page.Padding.HorizontalThickness, maxSheetHeight);
> > > 
> > >         return Math.Min(maxSheetHeight, r.Request.Height + page.Padding.VerticalThickness);
> > >     }
> > > }
> > > ```
> > 
> > 
> > I still caught some exceptions with that (apparently page can be null) but the following code fixed the issue for me
> > ```
> > public class FixedContentDetent : ContentDetent
> > {
> >     // HACK: https://github.com/the49ltd/The49.Maui.BottomSheet/issues/93
> >     public override double GetHeight(BottomSheet page, double maxSheetHeight)
> >     {
> >         if (page?.Content is null)
> >         {
> >             return maxSheetHeight;
> >         }
> > 
> >         // HACK: from 'page.Window.Width' to 'page.Window?.Width ?? page.Width' 
> >         var r = page.Content.Measure(page.Window?.Width ?? page.Width - page.Padding.HorizontalThickness, maxSheetHeight);
> > 
> >         return Math.Min(maxSheetHeight, r.Request.Height + page.Padding.VerticalThickness);
> >     }
> > }
> > ```
> 
> How do u guys put this override to work? Like where in the project that the bottomSheet get this modification.

You can put in anywhere.
The use this class instead ContentDetent in Xaml and add the namespace where you put this class to your BottomSheet Xaml.

Add this to the bottomsheet where other namespaces are: 

` xmlns:yournamespace="clr-namespace:MyNamespace“ `

and then use like this:

` <yournamespace:FixedContentDetent /> `
